name: Schedule 9:30 am Playwright e2e Test run

on:
  schedule:
    # Runs at 9:40 AM Brisbane time (AEST is UTC+10)
    - cron: '40 23 * * *' # This is UTC time; 9:30 AM AEST is 11:30 PM UTC of the previous day

jobs:
  trigger_playwright:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Playwright e2e Tests workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { github, context: githubContext } = require('@actions/github');
          await github.actions.createWorkflowDispatch({
            owner: githubContext.repo.owner,
            repo: githubContext.repo.repo,
            workflow_id: 'playwright.yml',
            ref: 'main'
          });