name: Scheduled 10:35 PM Playwright e2e Test run

on:
  schedule:
    # Runs at 10:35 PM Brisbane time (AEST is UTC+10)
    - cron: '35 12 * * *' # This is UTC time; 10:35 PM AEST is 12:35 PM UTC

jobs:
  trigger_playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright e2e Tests workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, getOctokit } = require('@actions/github');

            const octokit = getOctokit(process.env.GITHUB_TOKEN);
            
            await octokit.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'playwright.yml',
              ref: 'main'
            });
            console.log('Workflow dispatched successfully');