name: Scheduled 12:40 AM Playwright e2e Test run

on:
  schedule:
    # Runs at 12:40 AM Brisbane time (AEST is UTC+10)
    - cron: '40 14 * * *' # This is UTC time; 12:40 AM, AEST is 2:40 PM UTC

jobs:
  trigger_playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright e2e Tests workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            async function run() {
              try {
                const response = await github.rest.actions.createWorkflowDispatch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: 'playwright.yml',
                  ref: 'main'
                });
                console.log('Workflow dispatched successfully');
                console.log(response);
              } catch (error) {
                console.error('Error dispatching workflow:', error);
              }
            }
            
            run();