name: Scheduled 9:00 AM Playwright e2e Test run

on:
  schedule:
    # Runs at 9:00 AM Brisbane time (AEST is UTC+10)
    - cron: '0 23 * * *' # This is UTC time; 9:00 AM, AEST is 23:00 PM UTC

jobs:
  trigger_playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright e2e Tests workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_GITHUB }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'playwright.yml',
            ref: 'main'
            });