name: Scheduled 8:35 AM Playwright e2e Test run

on:
  schedule:
    # Runs at 8:35 AM Brisbane time (AEST is UTC+10)
    - cron: '35 22 * * *' # This is UTC time; 8:35 AM, AEST is 10:35 PM UTC

jobs:
  trigger_playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright e2e Tests workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'playwright.yml',
            ref: 'main'
            });