name: Scheduled 1:15 PM Playwright e2e Test run

on:
  schedule:
    # Runs at 1:15 PM Brisbane time (AEST is UTC+10)
    - cron: '15 3 * * *' # This is UTC time; 1:15 PM, AEST is 03:15 AM UTC

jobs:
  trigger_playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright e2e Tests workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_GITHUB }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'playwright.yml',
            ref: 'main'
            });