name: Scheduled 12:00 AM Playwright e2e Test run

on:
  schedule:
    # Runs at 10:35 PM Brisbane time (AEST is UTC+10)
    - cron: '0 14* * *' # This is UTC time; 10:35 PM AEST is 12:35 PM UTC

jobs:
  trigger_playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright e2e Tests workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            async function run() {
              try {
                await github.getOctokit(process.env.GITHUB_TOKEN).actions.createWorkflowDispatch({
                  owner: github.context.repo.owner,
                  repo: github.context.repo.repo,
                  workflow_id: 'playwright.yml',
                  ref: 'main'
                });
                console.log('Workflow dispatched successfully');
              } catch (error) {
                console.error('Error dispatching workflow:', error);
              }
            }
            
            run();