name: Scheduled 4:05 PM Playwright e2e Test run

on:
  schedule:
    # Runs at 4:05 PM Brisbane time (AEST is UTC+10)
    - cron: '5 6 * * *' # This is UTC time; 4:05 PM AEST is 6:05 AM UTC

jobs:
  trigger_playwright:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Playwright e2e Tests workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.actions.createWorkflowDispatch({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              workflow_id: 'playwright.yml',
              ref: 'main'
            });