name: Scheduled 5:15 PM Playwright e2e Test run

on:
  schedule:
    # Runs at 5:15 PM Brisbane time (AEST is UTC+10)
    - cron: '15 7 * * *' # This is UTC time; 5:15 PM AEST is 7:15 AM UTC

jobs:
  trigger_playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright e2e Tests workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = require('@actions/github');
            const context = github.context;

            async function run() {
              try {
                await github.getOctokit(process.env.GITHUB_TOKEN).actions.createWorkflowDispatch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: 'playwright.yml',
                  ref: 'main'
                });
                console.log('Workflow dispatched successfully');
              } catch (error) {
                console.error('Error dispatching workflow:', error);
              }
            }
            
            run();